### ISSUE TITLE
Document are not well displayed

### ISSUE THREAD

**Issue by heartsword2017** [graphql-java/graphql-java-page#25]
Hey, I am reading your document and find some places, they are not well displayed. Here is just an example. 
`https://github.com/graphql-java/graphql-java-page/blob/master/content/documentation/v13/instrumentation.md#field-validation-instrumentation`

Looks like it could be some templating problem?

**Comment by felipe-gdr** [comment]
@heartsword2017 what exactly is the problem you're experiencing?
That section looks ok in the webpage: https://www.graphql-java.com/documentation/v13/instrumentation/
