### ISSUE TITLE
a mistake 

### ISSUE THREAD

**Issue by jxnu-liguobin** [graphql-java/graphql-java-page#30]
Note that the semantics around the extended scalars might not be understood by your clients. For example mapping a Java Long (max value 26^3-1) into a JavaScript Number ( max value 2^53 - 1) may be problematic for you.

may be max value 2^63-1 ??

**Comment by felipe-gdr** [comment]
Hi @jxnu-liguobin, where in the docs have you seen a reference to Java Longs being mapped to JavaScript Numbers?

**Comment by bztsai** [comment]
@felipe-gdr it's fixed in this PR: https://github.com/graphql-java/graphql-java-page/pull/36
