### ISSUE TITLE
DataLoader is referenced in inconsistent ways and probably broken

### ISSUE THREAD

**Issue by benmccann** [graphql-java/graphql-java-page#35]
On https://www.graphql-java.com/documentation/v14/batching/:

Some places in the code have `environment.getDataLoader("characterLoader")` while others have `environment.getDataLoader("character")`. I'm guessing these are supposed to be the same?

It would be great if there were a more typesafe way of doing this to avoid these issues

**Comment by bbakerman** [comment]
> It would be great if there were a more typesafe way of doing this to avoid these issues

yeah so one trick is to use `env.getDataLoader(Some.class.getCanonicalName())`.

In practice this has not come up a lot and strings are very easy to use in other ways
