### ISSUE TITLE
 Inconsistent description in Directive-Section

### ISSUE THREAD

**Issue by knotenpunkt** [graphql-java/graphql-java-page#45]
hey:

https://www.graphql-java.com/documentation/v16/sdl-directives/

in the first example there is used a secound datafetcher on a direct way as wrapper:

`            // build a data fetcher that first checks authorisation roles before then calling the original data fetcher
            //
            DataFetcher originalDataFetcher = environment.getCodeRegistry().getDataFetcher(parentType, field);
            DataFetcher authDataFetcher = new DataFetcher() {
                @Override`

in the secound one, there is used a explicit datafetecher wrapper class:

` //
            // DataFetcherFactories.wrapDataFetcher is a helper to wrap data fetchers so that CompletionStage is handled correctly
            // along with POJOs
            //
            DataFetcher originalFetcher = environment.getCodeRegistry().getDataFetcher(parentType, field);
            DataFetcher dataFetcher = DataFetcherFactories.wrapDataFetcher(originalFetcher, ((dataFetchingEnvironment, value) -> {`

Do we need the wrapper class also for example 1) or dont we need it anymore on example 2?

Or are these examples correct? But for this we need maybe a short explanation why is these wrapper class explicit on example2 needed and not on example1

maybe anyway it would be good if someone can explain me here or there why CompletionStage isnt handled correctly along with POJOs if we dont use the wrapper-Class

**Comment by bbakerman** [comment]
This is a question and now that we have discussions we can continue it there
